Repository vtexdocs/dev-portal-content, pull requests merged in 2024-07, with the labels that each got.

#1289 (fix): faststore typos
  docs/faststore/components/features/regionalization.mdx
  docs/faststore/components/features/search.mdx
  docs/faststore/components/getting-started.mdx
  docs/faststore/docs/customization/building-sections/override-use-cases/overview.mdx
  docs/faststore/docs/customization/building-sections/overrides/component-props.mdx
  docs/faststore/docs/customization/building-sections/overrides/components-and-props-v1.mdx
  docs/faststore/docs/customization/building-sections/overrides/getoverriddensection-function.mdx
  docs/faststore/docs/customization/building-sections/overrides/native-component.mdx
  docs/faststore/docs/customization/building-sections/overrides/overview.mdx
  docs/faststore/docs/customization/using-themes/mixins-breakpoints.mdx
  docs/faststore/docs/customization/using-themes/overview.mdx
  docs/faststore/docs/getting-started/1-onboarding/overview.mdx
  docs/faststore/docs/getting-started/1-onboarding/starting-the-project.mdx
  docs/faststore/docs/getting-started/2-setting-up-the-project.mdx
  docs/faststore/docs/go-live/before-you-begin.mdx
  docs/faststore/docs/go-live/overview.mdx
  docs/faststore/docs/headless-cms/multiple-page-template.mdx
  docs/faststore/docs/headless-cms/overview.mdx
  docs/faststore/docs/headless-cms/widgets.mdx
  docs/faststore/docs/reference/global-tokens/overview.mdx
  docs/faststore/docs/reference/project-structure/custom-cypress.mdx
  docs/faststore/docs/troubleshooting/analytics-and-partytown.mdx
  docs/faststore/docs/troubleshooting/tracing-the-error-source.mdx
Labels: typo

#1291 Update how-to-interactively-inspect-blocks-on-a-store-framework-store.md
  docs/guides/vtex-io/Storefront-Guides/styling-your-store/how-to-interactively-inspect-blocks-on-a-store-framework-store.md
Labels: typo

#1311 24H1KR3: Extensibility
  docs/guides/VTEX-Platform-Overview/Extensibility/extensibility-overview.png
  docs/guides/VTEX-Platform-Overview/Extensibility/extensibility.md
Labels: new, documentation

#1196 EDU-12098 - Creating vtex-io-documentation-making-a-custom-component-available-in-site-editor.mdx
  docs/guides/vtex-io/Storefront-Guides/concepts-1/vtex-io-documentation-making-a-custom-component-available-in-site-editor.mdx
  docs/guides/vtex-io/Storefront-Guides/images/array-custom-component.png
  docs/guides/vtex-io/Storefront-Guides/images/array-item-custom-component.png
  docs/guides/vtex-io/Storefront-Guides/images/boolean-custom-component.png
  docs/guides/vtex-io/Storefront-Guides/images/default-schema.png
  docs/guides/vtex-io/Storefront-Guides/images/enum-enumname-example.png
  docs/guides/vtex-io/Storefront-Guides/images/enum-example.png
  docs/guides/vtex-io/Storefront-Guides/images/object-custom-component.png
  docs/guides/vtex-io/Storefront-Guides/images/string-date-custom-component.png
  docs/guides/vtex-io/Storefront-Guides/images/string-image-custom-component.png
Labels: documentation
