Repository vtexdocs/dev-portal-content, pull requests merged in 2024-06, with the labels that each got.

#1191 EDU-11196 - Creating Getting started with storefront solutions
  docs/guides/vtex-io/Storefront-Guides/getting-started-with-storefront-solutions.md
Labels: documentation

#1142 Quick win: Update native section link
  docs/faststore/docs/customization/building-sections/list-of-native-sections.mdx
Labels: quick-win

#1212 feat: EDU-11950 - configuring-dynamic-routes-in-vtex-io-services.md
  docs/guides/vtex-io/Getting-Started/back-end-development-guides/configuring-dynamic-routes-in-vtex-io-services.md
Labels: documentation

#1224 EDU-12635 - Creating testing-the-server-side-rendering.md
  docs/faststore/docs/managing-performance/testing-the-server-side-rendering.md
Labels: documentation

#1236 Update 3-faststore-cli.mdx
  docs/faststore/docs/getting-started/3-faststore-cli.mdx
Labels: typo

#1214 Doc: Updating Managing URL redirects
  docs/guides/vtex-io/Storefront-Guides/pages/vtex-io-documentation-managing-url-redirects.md
Labels: documentation

#1241 Doc: Creating vtex-io-documentation-creating-an-interface-for-your-app-settings.md
  docs/guides/vtex-io/Getting-Started/vtex-io-documentation-1-developing-storefront-apps-using-react-and-vtex-io/vtex-io-documentation-creating-an-interface-for-your-app-settings.md
Labels: documentation

#1255 Add Xcode to IO CLI install instructions
  docs/guides/vtex-io/Reference/vtex-io-documentation-vtex-io-cli-installation-and-command-reference/vtex-io-documentation-vtex-io-cli-install.md
Labels: quick-win, documentation

#1259 Update vtex-io-documentation-policies-from-license-manager.md
  docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-policies/vtex-io-documentation-policies-from-license-manager.md
Labels: markdown-error

#1258 EDU-12464 feat: add Displaying SLA by item in Checkout
  docs/guides/Checkout/customization.md
  docs/guides/Checkout/customization/displaying-sla-by-item-in-checkout.md
  docs/release-notes/2024-06-24-displaying-sla-by-item-in-checkout.md
  navigation.json
Labels: documentation
