Repository vtexdocs/dev-portal-content, pull requests merged in 2024-05, with the labels that each got.

#1118 Creating vtex-io-documentation-assets-builder.md
  docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-assets-builder.md
Labels: documentation

#1113 Creating vtex-io-documentation-store-builder.md
  docs/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-store-builder.md
Labels: documentation

#1139 fixes: vtex terminology
  docs/guides/Checkout/orderform-fields.md
  docs/guides/Integration-Guides/erp-integration-guide/erp-integration-set-up-catalog.md
  docs/guides/Integration-Guides/external-marketplace-integration-guide/external-marketplace-integration-guide.md
  docs/guides/Integration-Guides/external-seller-integration-guide/external-seller-integration-guide.md
  docs/guides/Integration-Guides/login-integration-guide.md
  docs/guides/Integration-Guides/search-integration-guide/external-search-provider-overview.md
  docs/guides/vtex-io/App-Guides/vtex-app-store/vtex-io-documentation-submitting-your-app-in-the-vtex-app-store.md
  docs/guides/vtex-io/Getting-Started/back-end-development-guides/how-to-connect-with-vtex-core-commerce-apis-using-vtex-io.md
  docs/guides/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-1-basicsetup.md
  docs/guides/vtex-io/Hello/welcome.md
  docs/guides/vtex-io/Perks/vtex-io-documentation-filling-the-application-form-for-development.md
  docs/guides/vtex-io/Reference/back-end-development-concepts/overview-of-vtex-io-services.md
  docs/guides/vtex-io/Storefront-Guides/boosting-performance/vtex-io-documentation-debugging-performance-issues.md
  docs/guides/vtex-io/Storefront-Guides/boosting-performance/vtex-io-documentation-safely-enabling-performance-settings.md
  docs/guides/vtex-io/Storefront-Guides/pages/vtex-io-documentation-enabling-404-pages.md
  docs/guides/vtex-io/Storefront-Guides/vtex-io-multi-language-stores.md
Labels: styleguide

#1140 Update icon.mdx
  docs/faststore/components/atoms/icon.mdx
Labels: chore

#1184 Quick win: Fix links
  docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-site-editor.md
  docs/guides/vtex-io/Storefront-Guides/vtex-io-documentation-going-live/vtex-io-documentation-migrating-storefront-from-legacy-to-io.md
Labels: quick-win
