Repository vtexdocs/dev-portal-content, pull requests merged in 2025-05, with the labels that each got.

#1876 Add GraphQL in VTEX IO section cover
  docs/guides/vtex-io/GraphQL/graphql-in-vtex-io.md
Labels: new, documentation

#1892 Doc reviewed by Localization
  docs/localization/vtex-io-documentation-graphql-builder.md
Labels: Localization

#1843 Add GraphQL builder documentation
  docs/guides/vtex-io/Reference/concepts/vtex-io-documentation-builders/vtex-io-documentation-graphql-builder.md
Labels: new, documentation

#1880 Apply Localization review
  docs/localization/modal.mdx
Labels: Localization

#1899 EDU-14919 feat: add release note
  docs/release-notes/2025-05-06-marketplace-api-new-affiliate-endpoints.md
Labels: documentation

#1915 Create tax-protocol-graphql-api.md
  docs/guides/Integration-Guides/tax-service-integration-guide/tax-protocol-graphql-api.md
Labels: new, documentation

#1925 Doc reviewed by Localization
  docs/localization/configuring-graphql-cache-control.mdx.md
Labels: Localization

#1927 Fix crowdin.yml file naming output
  crowdin.yml
Labels: Localization

#1938 Doc reviewed by Localization
  docs/localization/2025-05-30-graphql-cache-control.md_en
Labels: Localization

#1934 EDU-11430 - Fix variable name.
  docs/guides/Orders/orders-feed.md
Labels: documentation

#1909 Add "List of Apps GraphQL APIs"
  docs/localization/vtex-io-graphql-api-list.md
Labels: new, documentation

#1955 EDU-14329 - Update screenshot
  .DS_Store
  images/how-to-set-up-functions-in-the-message-center-templates-1.jpg
  images/how-to-set-up-functions-in-the-message-center-templates-1.png
Labels: documentation
