Repository vtexdocs/dev-portal-content, pull requests merged in 2025-06, with the labels that each got.

#2010 Remove Gift List docs
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-gift-list-listitemsorderby.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-gift-list-wrappers.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-addnewitem.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-addtolistbutton.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-authcondition.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-breadcrumbs.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-gallerylistitems.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-giftedbutton.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-gobacktolist.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-listaddtocartbutton.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-listinfo.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-listmigration.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-listmodal.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-productmodal.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-quantity-selector-1.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-quantity-selector-2.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-quantity-selector.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-searchlist.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-sharelist.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-storewalletlist.md
  docs/guides/vtex-io/Store-Framework-Apps/vtex-gift-list/vtex-list-userlists.md
Labels: documentation

#1989 Add "Check frontmatter" GitHub Action
  .github/scripts/check_frontmatter.py
  .github/workflows/check-frontmatter.yml
Labels: enhancement

#2001 Add "GraphQL Authorization in IO apps"
  docs/localization/graphql-authorization-in-io-apps.mdx
Labels: new, documentation

#2006 EDU-15440 - Add exception codes
  docs/guides/Integration-Guides/erp-integration-guide/order-modifications.md
Labels: documentation

#2038 Restore "GraphQL Authorization in IO apps"
  docs/guides/vtex-io/GraphQL/graphql-authorization-in-io-apps.mdx
Labels: documentation
